=== dart-lang/native/pkgs/hook/lib/schema/hook_output.schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "title": "Build Output Schema",
    "allOf": [
        {
            "$ref": "shared_definitions.schema.json#"
        }
    ],
    "type": "object",
    "properties": {
        "version": {
            "type": "string",
            "description": "Version of the build output"
        },
        "timestamp": {
            "type": "string",
            "description": "Timestamp of the build output"
        },
        "dependencies": {
            "type": "array",
            "description": "List of dependencies",
            "items": {
                "type": "string",
                "format": "uri-reference"
            }
        },
        "assets": {
            "type": "array",
            "description": "List of assets",
            "items": {
                "$ref": "shared_definitions.schema.json#/$defs/Asset"
            }
        }
    },
    "required": [
        "version",
        "timestamp"
    ]
}

=== dart-lang/native/pkgs/multiple_extensions/test/data/build_output.json
{
    "$schema": "../../lib/schema/build_output.schema.json",
    "version": "1.9.0",
    "timestamp": "2025-02-11 11:20:20.000",
    "dependencies": [
        "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_3.json",
        "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_2.json"
    ],
    "assets": [
        {
            "name": "assets/data_0.json",
            "package": "simple_link",
            "file": "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_0.json",
            "type": "data"
        },
        {
            "architecture": "arm64",
            "file": "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/iv6i0d/native_add/.dart_tool/native_assets_builder/native_add/c6b312c90c95d2d98ffb6760a738fb36/out/libnative_add.a",
            "id": "package:native_add/src/native_add_bindings_generated.dart",
            "link_mode": {
                "type": "static"
            },
            "os": "macos",
            "type": "native_code"
        }
    ]
}

=== dart-lang/native/pkgs/code_assets/test/data/build_output_ios.json
{
    "$schema": "../../lib/schema/build_output.schema.json",
    "version": "1.6.0",
    "timestamp": "2025-02-07 17:32:13.000",
    "dependencies": [
        "/Users/dacoharkes/src/dacoharkes/playground/my_package/src/my_package.c"
    ],
    "assets": [
        {
            "architecture": "arm64",
            "file": "/Users/dacoharkes/src/dacoharkes/playground/my_package/example/.dart_tool/native_assets_builder/my_package/51d66b45a7c440edc44bf124509a5dda/out/libmy_package.dylib",
            "id": "package:my_package/my_package_bindings_generated.dart",
            "link_mode": {
                "type": "dynamic_loading_bundle"
            },
            "os": "ios",
            "type": "native_code"
        }
    ]
}

=== dart-lang/native/pkgs/code_assets/test/data/link_output_macos.json
{
    "$schema": "../../lib/schema/link_output.schema.json",
    "version": "1.9.0",
    "timestamp": "2025-02-10 16:47:01.000",
    "dependencies": [
        "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/ZnD2I3/native_add/src/native_add.c"
    ],
    "assets": [
        {
            "architecture": "arm64",
            "file": "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/ZnD2I3/native_add/.dart_tool/native_assets_builder/native_add/14857adfaff1b1829b79c612288f54d7/out/libnative_add.dylib",
            "id": "package:native_add/src/native_add_bindings_generated.dart",
            "link_mode": {
                "type": "dynamic_loading_bundle"
            },
            "os": "macos",
            "type": "native_code"
        },
        {
            "architecture": "arm64",
            "id": "package:system_library/memory_system.dart",
            "link_mode": {
                "type": "dynamic_loading_system",
                "uri": "libc.dylib"
            },
            "os": "macos",
            "type": "native_code"
        },
        {
            "architecture": "arm64",
            "id": "package:system_library/memory_executable.dart",
            "link_mode": {
                "type": "dynamic_loading_executable"
            },
            "os": "macos",
            "type": "native_code"
        },
        {
            "architecture": "arm64",
            "id": "package:system_library/memory_process.dart",
            "link_mode": {
                "type": "dynamic_loading_process"
            },
            "os": "macos",
            "type": "native_code"
        },
        {
            "architecture": "arm64",
            "file": "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/iv6i0d/native_add/.dart_tool/native_assets_builder/native_add/c6b312c90c95d2d98ffb6760a738fb36/out/libnative_add.a",
            "id": "package:native_add/src/native_add_bindings_generated.dart",
            "link_mode": {
                "type": "static"
            },
            "os": "macos",
            "type": "native_code"
        }
    ]
}

=== dart-lang/native/pkgs/hooks/test/data/build_output_windows.json
{
  "$schema": "../../doc/schema/hook/build_output.generated.schema.json",
  "assets": [
    {
      "architecture": "x64",
      "file": "C:\\src\\dacoharkes\\playground\\my_package\\example\\.dart_tool\\native_assets_builder\\my_package\\190c04c47dc2f9eb26d2411b1968b2cf\\out\\my_package.dll",
      "id": "package:my_package/my_package_bindings_generated.dart",
      "link_mode": {
        "type": "dynamic_loading_bundle"
      },
      "os": "windows",
      "type": "native_code"
    }
  ],
  "dependencies": [
    "C:\\src\\dacoharkes\\playground\\my_package\\src\\my_package.c"
  ],
  "timestamp": "2025-02-17 09:57:36.000",
  "version": "1.9.0"
}

=== dart-lang/native/pkgs/hook/test/data/link_output.json
{
  "$schema": "../../doc/schema/hook/link_output.schema.json",
  "assets": [
    {
      "some_key": "some_value",
      "type": "some_asset_type"
    },
    {
      "some_other_key": "some_value",
      "type": "some_other_asset_type"
    }
  ],
  "dependencies": [
    "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_2.json",
    "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_3.json"
  ],
  "timestamp": "2025-02-11 11:20:20.000",
  "version": "1.9.0"
}

=== dart-lang/native/pkgs/code_assets/test/data/build_output_linux.json
{
  "$schema": "../../doc/schema/hook/build_output.generated.schema.json",
  "assets": [
    {
      "architecture": "x64",
      "encoding": {
        "architecture": "x64",
        "file": "file:///usr/local/google/home/dacoharkes/src/dacoharkes/playground/my_package/example/.dart_tool/native_assets_builder/my_package/79cc7fbaec53b1465c3e388e6848234b/out/libmy_package.so",
        "id": "package:my_package/my_package_bindings_generated.dart",
        "link_mode": {
          "type": "dynamic_loading_bundle"
        },
        "os": "linux"
      },
      "file": "file:///usr/local/google/home/dacoharkes/src/dacoharkes/playground/my_package/example/.dart_tool/native_assets_builder/my_package/79cc7fbaec53b1465c3e388e6848234b/out/libmy_package.so",
      "id": "package:my_package/my_package_bindings_generated.dart",
      "link_mode": {
        "type": "dynamic_loading_bundle"
      },
      "os": "linux",
      "type": "native_code"
    }
  ],
  "dependencies": [
    "file:///usr/local/google/home/dacoharkes/src/dacoharkes/playground/my_package/src/my_package.c"
  ],
  "timestamp": "2025-02-17 17:36:39.000",
  "version": "1.9.0"
}

=== dart-lang/native/pkgs/data_assets/test/data/link_output.json
{
    "$schema": "../../lib/schema/link_output.schema.json",
    "version": "1.9.0",
    "timestamp": "2025-02-11 11:20:20.000",
    "dependencies": [
        "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_3.json",
        "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_2.json"
    ],
    "assets": [
        {
            "name": "assets/data_0.json",
            "package": "simple_link",
            "file": "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_0.json",
            "type": "data"
        },
        {
            "name": "assets/data_1.json",
            "package": "simple_link",
            "file": "/private/var/folders/2y/mngq9h194yzglt4kzttzfq6800klzg/T/0s5bKi/simple_link/assets/data_1.json",
            "type": "data"
        }
    ]
}
